#Error while connecting: tcpip::Socket::connect() @ connect: Connection refused
Warning: Using old TraCI API, please update your client!
Error: Answered with error to command 115: Point of interest with internal id notexisting_poi not existing
